version: '3'

services:

    server:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: 'server'
        command: python manage.py runserver 0:8000
        volumes:
            - .:/code
        ports:
            - '8000:8000'

    redis:
        image: bitnami/redis:latest
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        volumes:
          - ./redis/data:/bitnami/redis/data
        ports:
          - 6379:6379
        depends_on:
          - server

    celery:
        build: .
        command: celery -A test_blog worker -l info
        volumes:
            - .:/code
        depends_on:
            - server
            - redis

    # front:
    #     container_name: front
    #     build:
    #         context: ./frontend
    #         dockerfile: Dockerfile
    #     volumes:
    #         - './frontend:/app'
    #         - '/app/node_modules'
    #     ports:
    #         - '3000:3000'
    #     environment:
    #         - NODE_ENV=development
    #         # - CHOKIDAR_USEPOLLING=true
    #     depends_on:
    #         - server

#    admin_panel:
#        container_name: admin_panel
#        build:
#            context: ./admin_panel
#            dockerfile: Dockerfile
#        volumes:
#            - './admin_panel:/admin_app'
#            - '/admin_app/node_modules'
#        ports:
#            - '3100:3000'
#        environment:
#            - NODE_ENV=development
#            # - CHOKIDAR_USEPOLLING=true
#        depends_on:
#            - server
#volumes:
#    psql_database:
